### ISSUE TITLE
Se puede simplificar el test

### ISSUE THREAD

**Issue by evolentini** [fedealde/leds#1]
Esta prueba

https://github.com/fedealde/leds/blob/cda0f8c7b98ce60d2022ce458f7f1803dae6def6/test/test_leds.c#L102-L108

se puedes implicar a esta versión

```c
// Consultar el estado de un LED que esta apagado 
 void test_consultar_por_led_apagado(void) { 
     TEST_ASSERT_FALSE(LedsIsOn(12)); 
 } 
```

ya que hay un requisito que pide que los leds arranquen apagados

**Comment by fedealde** [comment]
TP corregido, gracias!
